export const certificates = [
  {
    id: '1',
    title: 'AgileScrum.title',
    date: new Date('06/13/2023'),
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    instructor: 'Alex Kostritsa',
    uri: 'https://www.udemy.com/certificate/UC-6e3bba7d-d2de-4ac6-9251-a66194547e20/',
    image: '/certificates/agile.jpg',
  },
  {
    id: '2',
    title: 'NodeJSAuthentication.title',
    date: new Date('01/16/2024'),
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    instructor: 'Bassam Guide',
    uri: 'https://www.udemy.com/certificate/UC-7d2723f4-bf7f-4e66-bde4-64b5547a096c/',
    image: '/certificates/nodejsauth.jpg',
  },
  {
    id: '3',
    title: 'NodeJSFull.title',
    date: new Date('01/19/2024'),
    instructor: 'Bogdan Stashchuk',
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    uri: 'https://www.udemy.com/certificate/UC-30b69a78-09d3-4b1f-8dd6-7ceba96a25cc/',
    image: '/certificates/nodejs.jpg',
  },
  {
    id: '4',
    title: 'ReactNext.title',
    date: new Date('01/15/2024'),
    instructor: 'Anton Larichev',
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    uri: 'https://www.udemy.com/certificate/UC-8657b786-53c8-4671-9940-176ee6e12834/',
    image: '/certificates/reactnextlarichev.jpg',
  },
  {
    id: '5',
    title: 'GraphQL.title',
    date: new Date('05/08/2024'),
    instructor: 'Mirko Nasato',
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    uri: 'https://www.udemy.com/certificate/UC-d1836f88-708e-46ff-873c-5d2309e22d23/',
    image: '/certificates/graphql.jpg',
  },
  {
    id: '6',
    title: 'NextJSReact.title',
    date: new Date('01/31/2024'),
    instructor: 'Maximilian Schwarzmüller',
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    uri: 'https://www.udemy.com/certificate/UC-79a6ec72-e612-4cf1-b95d-b88298fd54fc/',
    image: '/certificates/nextreact.jpg',
  },
  {
    id: '7',
    title: 'TypeScript.title',
    date: new Date('08/09/2022'),
    instructor: 'Anton Larichev',
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    uri: 'https://www.udemy.com/certificate/UC-075f827a-a5fd-4020-bb72-c90b9c168548/',
    image: '/certificates/typescript.jpg',
  },
  {
    id: '8',
    title: 'NestJS.title',
    date: new Date('05/31/2024'),
    instructor: 'Anton Larichev',
    platform: {
      name: 'Udemy',
      uri: 'https://www.udemy.com/',
    },
    uri: 'https://www.udemy.com/certificate/UC-67952c7c-b1b1-4ab4-8ee3-b8158213405e/',
    image: '/certificates/nestjs.jpg',
  },
  {
    id: '9',
    title: 'RSSchool.title',
    date: new Date('10/14/2018'),
    instructor: 'Dzmitry Varabei',
    platform: {
      name: 'Rolling Scopes School',
      uri: 'https://rs.school/',
    },
    uri: '',
    image: '/certificates/RSSchool.jpg',
  },
];
