export const workExperience = {
  bemn: {
    company: 'bemn.company',
    position: 'bemn.position',
    start: new Date(2014, 8), // September 2014
    end: new Date(2016, 9), // October 2016
    location: 'minsk',
    description: 'bemn.description',
    logo: '/bemn.png',
    size: { width: 75, height: 90 },
    contactor: [],
  },
  epamBelarus: {
    company: 'epam.company',
    position: 'epam.position',
    start: new Date(2018, 9),
    end: new Date(2023, 4),
    location: 'minsk',
    description: 'epam.description',
    logo: '/epam-logo.png',
    size: { width: 180, height: 50 },
    remote: false,
    contactor: [
      {
        company: 'thomson.company',
        position: 'thomson.position',
        start: new Date(2018, 9),
        end: new Date(2019, 3),
        location: 'minsk',
        description: 'thomson.description',
        logo: '/tr-logo.png',
        size: { width: 75, height: 70 },
        remote: true,
      },
      {
        company: 'refinitiv.company',
        position: 'refinitiv.position',
        start: new Date(2019, 3),
        end: new Date(2022, 0),
        location: 'minsk',
        description: 'refinitiv.description',
        logo: '/refinitiv-logo.png',
        size: { width: 55, height: 50 },
        remote: true,
      },
      {
        company: 'lseg.company',
        position: 'lseg.position',
        start: new Date(2022, 0),
        end: new Date(2023, 11),
        location: 'minsk',
        description: 'lseg.description',
        logo: '/lseg-logo.png',
        size: { width: 110, height: 80 },
        remote: true,
      },
    ],
  },
  epamPoland: {
    company: 'epam.company',
    position: 'epam.position',
    start: new Date(2023, 4),
    end: new Date(2024, 4),
    location: 'warsaw',
    description: 'epam.description',
    logo: '/epam-logo.png',
    size: { width: 180, height: 50 },
    remote: false,
    contactor: [
      {
        company: 'lseg.company',
        position: 'lseg.position',
        start: new Date(2023, 4),
        end: new Date(2023, 11),
        location: 'warsaw',
        description: 'lseg.description',
        logo: '/lseg-logo.png',
        size: { width: 110, height: 80 },
        remote: false,
      },
    ],
  },
};
